Community Tickets Integration
mt-support/tribe-ext-per-event-checkin-api pull request #3
Opened 2021-06-28 10:08 UTC by rafsuntaskin

Individual API for each event is now shown on the Community Event edit pages:

![Uploading Screen Shot 2021-06-28 at 4.08.03 PM.png…]()

2021-06-29 17:03 UTC, bordoni requested changes

2021-06-29 17:03 UTC, bordoni commented on src/Tribe/Api_Handler.php
> +		$uri = $_SERVER[ 'REQUEST_URI' ];
Make sure we check if this variable exists before we use it.

2021-06-29 17:03 UTC, bordoni commented on src/Tribe/Api_Handler.php
> +					?>
```suggestion
					<?php esc_html_e( 'Event API Key', 'et-per-event-checkin' ); ?>
```

2021-06-29 17:03 UTC, bordoni commented on src/Tribe/Api_Handler.php
> +				?>
```suggestion
				<?php $this->render_event_tickets_api_meta_box( $post ); ?>
```

2022-05-18 07:56 UTC, juanfra approved these changes
🚀

2022-05-18 10:43 UTC, merged